var LABELS = {
  youth: "청년지원",
  smallbiz: "소상공인",
  startup: "창업지원",
  housing: "주거지원",
  welfare: "복지혜택",
  local: "지역별 지원금",
  open: "공고 확인",
  deadline: "마감 확인",
  period: "기간",
  end: "마감",
  check: "공식 공고 확인"
};

var STATIC_ARTICLES = {
  "youth-rent": "youth-rent.html",
  "kua-youth": "kua-youth.html",
  "youth-leap-account": "youth-leap-account.html",
  "youth-job": "youth-job.html",
  "youth-saving": "youth-saving.html",
  "smallbiz-fund": "smallbiz-fund.html",
  "smallbiz-digital": "smallbiz-digital.html",
  "smallbiz-electric": "smallbiz-electric.html",
  "smallbiz-return": "smallbiz-return.html",
  "startup-basic": "startup-basic.html",
  "startup-pre": "startup-pre.html",
  "startup-leap": "startup-leap.html",
  "tips": "tips.html",
  "jeonse": "jeonse.html",
  "housing-benefit": "housing-benefit.html",
  "youth-jeonse-guarantee": "youth-jeonse-guarantee.html",
  "lh-youth-jeonse": "lh-youth-jeonse.html",
  "eitc": "eitc.html",
  "child-tax-credit": "child-tax-credit.html",
  "culture": "culture.html",
  "energy": "energy.html",
  "child-care": "child-care.html",
  "seoul-youth": "seoul-youth.html"
};

window.SUPPORT_PROGRAMS = [
  ["youth-rent", "청년 월세 한시 특별지원", "youth", "open", LABELS.period, LABELS.check, "만 19~34세 무주택 청년", "월 최대 20만원", "복지로", "https://www.bokjiro.go.kr/"],
  ["kua-youth", "국민취업지원제도 청년층 지원", "youth", "open", LABELS.period, "상시 신청 확인", "취업을 준비하는 청년", "취업지원서비스 및 구직촉진수당", "고용24", "https://www.work24.go.kr/"],
  ["youth-leap-account", "청년도약계좌", "youth", "open", LABELS.period, "월별 신청기간 확인", "소득요건을 충족한 청년", "정부기여금 및 비과세 혜택", "서민금융진흥원", "https://ylaccount.kinfa.or.kr/"],
  ["youth-job", "청년 취업성공수당", "youth", "deadline", LABELS.end, LABELS.check, "취업지원 프로그램 참여 청년", "최대 150만원", "고용24", "https://www.work24.go.kr/"],
  ["youth-saving", "청년내일저축계좌", "youth", "open", LABELS.period, "복지로 모집공고 확인", "근로 중인 저소득 청년", "자산형성 지원", "복지로", "https://www.bokjiro.go.kr/"],
  ["youth-mind", "청년 마음건강 지원사업", "youth", "open", LABELS.period, "복지로 또는 지자체 확인", "심리상담이 필요한 청년", "전문 심리상담 바우처", "복지로", "https://www.bokjiro.go.kr/"],
  ["youth-exam-fee", "청년 국가기술자격시험 응시료 지원", "youth", "open", LABELS.period, "Q-Net 접수일정 확인", "국가기술자격 응시 청년", "응시료 일부 지원", "Q-Net", "https://www.q-net.or.kr/"],
  ["youth-job-dojak", "청년일자리도약장려금", "youth", "open", LABELS.period, "고용노동부 공고 확인", "청년을 채용한 기업", "채용장려금 지원", "고용노동부", "https://www.moel.go.kr/"],
  ["youth-housing-separate", "청년 주거급여 분리지급", "youth", "open", LABELS.period, "상시 신청 확인", "부모와 따로 거주하는 청년", "임차료 별도 지원", "복지로", "https://www.bokjiro.go.kr/"],

  ["smallbiz-digital", "소상공인 디지털 전환 지원사업", "smallbiz", "open", LABELS.period, "기관별 공고 확인", "소상공인", "최대 100만원", "소상공인24", "https://www.sbiz24.kr/"],
  ["smallbiz-fund", "소상공인 정책자금", "smallbiz", "open", LABELS.period, "자금별 접수일정 확인", "소상공인 및 자영업자", "정책자금 융자", "소상공인정책자금", "https://ols.semas.or.kr/"],
  ["smallbiz-electric", "소상공인 전기요금 특별지원", "smallbiz", "open", LABELS.period, LABELS.check, "전기요금 부담 소상공인", "전기요금 일부 지원", "소상공인24", "https://www.sbiz24.kr/"],
  ["smallbiz-online", "소상공인 온라인 판로지원", "smallbiz", "open", LABELS.period, "소상공인24 공고 확인", "온라인 진출 희망 소상공인", "판로·마케팅 지원", "소상공인24", "https://www.sbiz24.kr/"],
  ["smallbiz-consulting", "소상공인 컨설팅 지원", "smallbiz", "open", LABELS.period, "기관별 공고 확인", "경영개선 희망 소상공인", "전문 컨설팅 지원", "소상공인시장진흥공단", "https://www.sbiz.or.kr/"],
  ["smallbiz-return", "희망리턴패키지", "smallbiz", "open", LABELS.period, LABELS.check, "폐업 또는 재창업 소상공인", "재기교육·컨설팅·사업화 지원", "소상공인시장진흥공단", "https://www.sbiz.or.kr/"],
  ["smallbiz-market", "전통시장 및 상점가 활성화 지원", "smallbiz", "open", LABELS.period, "공고별 확인", "전통시장·상점가·상인회", "시설·마케팅·경영 지원", "소상공인시장진흥공단", "https://www.sbiz.or.kr/"],
  ["smallbiz-clean", "소공인 클린제조환경 조성", "smallbiz", "open", LABELS.period, LABELS.check, "제조업 소공인", "작업환경 개선 지원", "소상공인시장진흥공단", "https://www.sbiz.or.kr/"],

  ["startup-basic", "초기 창업패키지", "startup", "open", LABELS.period, "K-Startup 공고 확인", "초기 창업기업", "사업화 자금", "K-Startup", "https://www.k-startup.go.kr/"],
  ["startup-pre", "예비창업패키지", "startup", "open", LABELS.period, "K-Startup 공고 확인", "예비창업자", "사업화 자금 및 멘토링", "K-Startup", "https://www.k-startup.go.kr/"],
  ["startup-leap", "창업 도약패키지", "startup", "deadline", LABELS.end, "K-Startup 공고 확인", "도약기 창업기업", "최대 3억원", "K-Startup", "https://www.k-startup.go.kr/"],
  ["tips", "TIPS 프로그램", "startup", "open", LABELS.period, LABELS.check, "기술창업 스타트업", "투자연계 R&D 지원", "TIPS", "https://www.jointips.or.kr/"],
  ["startup-school", "신사업창업사관학교", "startup", "open", LABELS.period, "모집공고 확인", "예비창업자", "교육·점포체험·사업화 지원", "소상공인시장진흥공단", "https://www.sbiz.or.kr/"],
  ["startup-rnd", "창업성장기술개발사업", "startup", "open", LABELS.period, "중소기업기술개발 공고 확인", "기술 기반 창업기업", "R&D 자금 지원", "SMTECH", "https://www.smtech.go.kr/"],
  ["startup-retry", "재도전성공패키지", "startup", "open", LABELS.period, LABELS.check, "재창업자", "재창업 사업화 지원", "K-Startup", "https://www.k-startup.go.kr/"],
  ["startup-open-innovation", "민관협력 오픈이노베이션 지원", "startup", "open", LABELS.period, "K-Startup 공고 확인", "스타트업 및 창업기업", "대기업 협업·사업화 지원", "K-Startup", "https://www.k-startup.go.kr/"],

  ["jeonse", "버팀목 전세자금대출", "housing", "open", LABELS.period, "상품별 확인", "무주택 세대주", "전세자금 대출", "주택도시기금", "https://nhuf.molit.go.kr/"],
  ["newlywed", "신혼부부 전세자금 대출이자 지원", "housing", "open", LABELS.period, "지자체 공고 확인", "신혼부부", "이자 일부 지원", "정부24", "https://www.gov.kr/"],
  ["housing-benefit", "주거급여", "housing", "open", LABELS.period, "상시 신청 확인", "소득인정액 기준 가구", "임차료 또는 수선유지비 지원", "복지로", "https://www.bokjiro.go.kr/"],
  ["youth-jeonse-guarantee", "청년 전세보증금 반환보증 보증료 지원", "housing", "deadline", LABELS.end, "정부24 공고 확인", "청년 임차인", "보증료 일부 지원", "정부24", "https://www.gov.kr/"],
  ["lh-youth-jeonse", "LH 청년전세임대", "housing", "open", LABELS.period, "LH 모집공고 확인", "대학생·취업준비생·청년", "전세임대 지원", "LH 청약플러스", "https://apply.lh.or.kr/"],
  ["happy-house", "행복주택 입주자 모집", "housing", "open", LABELS.period, "LH·SH 공고 확인", "청년·신혼부부·고령자", "공공임대주택 공급", "LH 청약플러스", "https://apply.lh.or.kr/"],
  ["newlywed-butimok", "신혼부부 버팀목 전세자금", "housing", "open", LABELS.period, "주택도시기금 확인", "신혼부부 무주택 세대주", "전세자금 대출 지원", "주택도시기금", "https://nhuf.molit.go.kr/"],

  ["eitc", "근로장려금", "welfare", "open", LABELS.period, "국세청 신청기간 확인", "소득요건 충족 가구", "가구유형별 지급", "국세청 홈택스", "https://www.hometax.go.kr/"],
  ["child-tax-credit", "자녀장려금", "welfare", "open", LABELS.period, "국세청 신청기간 확인", "부양자녀가 있는 저소득 가구", "자녀 1인당 차등 지급", "국세청 홈택스", "https://www.hometax.go.kr/"],
  ["culture", "문화누리카드", "welfare", "open", LABELS.period, "연도별 확인", "기초생활수급자·차상위계층", "문화·여행 바우처", "문화누리", "https://www.mnuri.kr/"],
  ["energy", "에너지바우처", "welfare", "open", LABELS.period, LABELS.check, "취약계층 가구", "에너지비 지원", "에너지바우처", "https://www.energyv.or.kr/"],
  ["child-care", "아이돌봄서비스 정부지원", "welfare", "open", LABELS.period, "상시 신청 확인", "돌봄이 필요한 가정", "돌봄 이용요금 일부 지원", "아이돌봄서비스", "https://www.idolbom.go.kr/"],
  ["basic-living", "기초생활보장 생계급여", "welfare", "open", LABELS.period, "상시 신청 확인", "소득인정액 기준 충족 가구", "생계급여 지원", "복지로", "https://www.bokjiro.go.kr/"],
  ["lifelong-voucher", "평생교육바우처", "welfare", "open", LABELS.period, LABELS.check, "교육 취약계층 성인", "교육비 바우처", "평생교육바우처", "https://www.lllcard.kr/"],
  ["disabled-activity", "장애인활동지원", "welfare", "open", LABELS.period, "상시 신청 확인", "활동지원이 필요한 장애인", "활동지원급여 제공", "복지로", "https://www.bokjiro.go.kr/"],

  ["seoul-youth", "서울시 청년수당", "local", "open", LABELS.period, "서울시 공고 확인", "서울 거주 청년", "활동지원금", "청년몽땅정보통", "https://youth.seoul.go.kr/"],
  ["seoul-saving", "서울시 희망두배 청년통장", "local", "open", LABELS.period, "서울시 공고 확인", "서울 거주 근로 청년", "저축액 매칭 지원", "청년몽땅정보통", "https://youth.seoul.go.kr/"],
  ["gg-youth", "경기도 청년기본소득", "local", "open", LABELS.period, "경기도 공고 확인", "경기도 거주 청년", "분기별 지원", "잡아바", "https://apply.jobaba.net/"],
  ["gg-worker-bank", "경기도 청년 노동자 통장", "local", "open", LABELS.period, "경기도 공고 확인", "경기도 거주 청년 노동자", "자산형성 지원", "경기청년포털", "https://youth.gg.go.kr/"],
  ["busan-youth", "부산 청년 디딤돌카드", "local", "open", LABELS.period, "부산시 공고 확인", "부산 거주 청년", "활동비 지원", "부산광역시", "https://www.busan.go.kr/"],
  ["incheon-exam", "인천 청년 자격증 응시료 지원", "local", "open", LABELS.period, "인천시 공고 확인", "인천 거주 청년", "응시료 일부 지원", "인천광역시", "https://www.incheon.go.kr/"],
  ["daejeon-rent", "대전 청년 월세지원", "local", "open", LABELS.period, "대전시 공고 확인", "대전 거주 청년", "월세 일부 지원", "대전광역시", "https://www.daejeon.go.kr/"],
  ["gwangju-dream", "광주 청년드림수당", "local", "open", LABELS.period, "광주시 공고 확인", "광주 거주 미취업 청년", "구직활동비 지원", "광주광역시", "https://www.gwangju.go.kr/"]
].map(function (item) {
  var categoryKey = item[2];
  var statusKey = item[3];
  return {
    slug: item[0],
    title: item[1],
    categoryKey: categoryKey,
    category: LABELS[categoryKey],
    categoryTone: categoryKey === "youth" ? "blue" : categoryKey === "smallbiz" || categoryKey === "local" ? "mint" : categoryKey === "startup" ? "orange" : "purple",
    status: LABELS[statusKey],
    statusTone: statusKey === "deadline" ? "amber" : "green",
    group: statusKey === "deadline" ? "deadline" : "open",
    periodLabel: item[4],
    period: item[5],
    target: item[6],
    amount: item[7],
    sourceName: item[8],
    sourceUrl: item[9],
    link: STATIC_ARTICLES[item[0]] || ("./article.html?slug=" + item[0]),
    updatedAt: "2026-06-24"
  };
});
