window.SUPPORT_PROGRAMS = [
  {
    title: "청년 월세 한시 특별지원",
    category: "청년지원",
    categoryTone: "blue",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "공식 공고 확인",
    target: "만 19~34세 청년",
    amount: "월 최대 20만원",
    link: "./posts/youth-rent-special-support.html",
    sourceName: "복지로",
    sourceUrl: "https://www.bokjiro.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "소상공인 디지털 전환 지원사업",
    category: "소상공인",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "기관별 공고 확인",
    target: "소상공인",
    amount: "최대 100만원",
    link: "./posts/small-business-digital.html",
    sourceName: "소상공인24",
    sourceUrl: "https://www.sbiz24.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "초기 창업패키지 지원사업",
    category: "창업지원",
    categoryTone: "orange",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "K-Startup 공고 확인",
    target: "예비창업자, 3년 이내 창업기업",
    amount: "최대 1억원",
    link: "./posts/startup-package.html",
    sourceName: "K-Startup",
    sourceUrl: "https://www.k-startup.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "신혼부부 전세자금 대출이자 지원",
    category: "주거지원",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "지자체 공고 확인",
    target: "신혼부부",
    amount: "연 최대 100만원",
    link: "./posts/newlywed-jeonse-loan.html",
    sourceName: "정부24",
    sourceUrl: "https://www.gov.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "청년 취업성공수당",
    category: "청년지원",
    categoryTone: "blue",
    status: "마감임박",
    statusTone: "amber",
    group: "deadline",
    periodLabel: "마감",
    period: "공식 공고 확인",
    target: "만 18~34세 미취업 청년",
    amount: "최대 150만원",
    link: "./posts/job-success-allowance.html",
    sourceName: "고용24",
    sourceUrl: "https://www.work24.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "소상공인 경영환경 개선사업",
    category: "소상공인",
    categoryTone: "mint",
    status: "마감임박",
    statusTone: "amber",
    group: "deadline",
    periodLabel: "마감",
    period: "기관별 공고 확인",
    target: "소상공인",
    amount: "최대 200만원",
    link: "./posts/management-improvement.html",
    sourceName: "소상공인시장진흥공단",
    sourceUrl: "https://www.sbiz.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "창업 도약패키지 지원사업",
    category: "창업지원",
    categoryTone: "orange",
    status: "마감임박",
    statusTone: "amber",
    group: "deadline",
    periodLabel: "마감",
    period: "K-Startup 공고 확인",
    target: "3~7년 이내 창업기업",
    amount: "최대 3억원",
    link: "./posts/startup-leap-package.html",
    sourceName: "K-Startup",
    sourceUrl: "https://www.k-startup.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "청년 전세보증금 반환보증 보증료 지원",
    category: "주거지원",
    categoryTone: "purple",
    status: "마감임박",
    statusTone: "amber",
    group: "deadline",
    periodLabel: "마감",
    period: "정부24 공고 확인",
    target: "만 19~34세 청년",
    amount: "최대 30만원",
    link: "./posts/youth-jeonse-return.html",
    sourceName: "정부24",
    sourceUrl: "https://www.gov.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "긴급복지 생계지원",
    category: "복지혜택",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "상시 또는 지자체 확인",
    target: "위기상황 발생 가구",
    amount: "가구원 수별 차등 지원",
    link: "https://www.bokjiro.go.kr/",
    sourceName: "복지로",
    sourceUrl: "https://www.bokjiro.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "에너지바우처",
    category: "복지혜택",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "공식 공고 확인",
    target: "취약계층 가구",
    amount: "가구별 차등 지원",
    link: "https://www.energyv.or.kr/",
    sourceName: "에너지바우처",
    sourceUrl: "https://www.energyv.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "서울시 청년수당",
    category: "지역별 지원금",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "서울시 공고 확인",
    target: "서울 거주 미취업 청년",
    amount: "공고별 확인",
    link: "https://youth.seoul.go.kr/",
    sourceName: "청년몽땅정보통",
    sourceUrl: "https://youth.seoul.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "경기도 청년기본소득",
    category: "지역별 지원금",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "경기도 공고 확인",
    target: "경기도 거주 청년",
    amount: "분기별 지원",
    link: "https://apply.jobaba.net/",
    sourceName: "잡아바 어플라이",
    sourceUrl: "https://apply.jobaba.net/",
    updatedAt: "2026-06-23"
  },
  {
    title: "국민취업지원제도 청년층 지원",
    category: "청년지원",
    categoryTone: "blue",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "상시 신청 확인",
    target: "취업을 준비하는 청년",
    amount: "구직촉진수당 등",
    link: "./posts/kua-youth-job-support.html",
    sourceName: "국민취업지원제도",
    sourceUrl: "https://www.kua.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "청년도약계좌",
    category: "청년지원",
    categoryTone: "blue",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "월별 신청기간 확인",
    target: "소득요건을 충족한 청년",
    amount: "정부기여금 및 비과세 혜택",
    link: "./posts/youth-leap-account.html",
    sourceName: "서민금융진흥원",
    sourceUrl: "https://ylaccount.kinfa.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "청년일자리도약장려금",
    category: "청년지원",
    categoryTone: "blue",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "고용노동부 공고 확인",
    target: "청년 채용 기업",
    amount: "채용장려금 지원",
    link: "https://www.work24.go.kr/",
    sourceName: "고용24",
    sourceUrl: "https://www.work24.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "소상공인 정책자금",
    category: "소상공인",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "자금별 접수일정 확인",
    target: "소상공인 및 자영업자",
    amount: "정책자금 융자",
    link: "https://ols.semas.or.kr/",
    sourceName: "소상공인정책자금",
    sourceUrl: "https://ols.semas.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "전통시장 및 상점가 활성화 지원",
    category: "소상공인",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "공고별 확인",
    target: "전통시장, 상점가, 상인회",
    amount: "사업별 차등 지원",
    link: "https://www.sbiz.or.kr/",
    sourceName: "소상공인시장진흥공단",
    sourceUrl: "https://www.sbiz.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "희망리턴패키지",
    category: "소상공인",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "공식 공고 확인",
    target: "폐업 또는 재창업 소상공인",
    amount: "컨설팅 및 사업화 지원",
    link: "https://www.sbiz.or.kr/",
    sourceName: "소상공인시장진흥공단",
    sourceUrl: "https://www.sbiz.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "예비창업패키지",
    category: "창업지원",
    categoryTone: "orange",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "K-Startup 공고 확인",
    target: "예비창업자",
    amount: "사업화 자금 지원",
    link: "./posts/pre-startup-package.html",
    sourceName: "K-Startup",
    sourceUrl: "https://www.k-startup.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "창업중심대학 지원사업",
    category: "창업지원",
    categoryTone: "orange",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "주관기관 공고 확인",
    target: "예비창업자 및 창업기업",
    amount: "사업화 및 보육 지원",
    link: "https://www.k-startup.go.kr/",
    sourceName: "K-Startup",
    sourceUrl: "https://www.k-startup.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "재도전성공패키지",
    category: "창업지원",
    categoryTone: "orange",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "공식 공고 확인",
    target: "재창업자",
    amount: "사업화 자금 및 멘토링",
    link: "https://www.k-startup.go.kr/",
    sourceName: "K-Startup",
    sourceUrl: "https://www.k-startup.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "버팀목 전세자금대출",
    category: "주거지원",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "상품별 확인",
    target: "무주택 세대주",
    amount: "전세자금 대출 지원",
    link: "./posts/butimok-jeonse-loan.html",
    sourceName: "주택도시기금",
    sourceUrl: "https://nhuf.molit.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "청년전용 버팀목 전세자금",
    category: "주거지원",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "상품별 확인",
    target: "청년 무주택 세대주",
    amount: "전세자금 대출 지원",
    link: "https://nhuf.molit.go.kr/",
    sourceName: "주택도시기금",
    sourceUrl: "https://nhuf.molit.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "주거급여",
    category: "주거지원",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "상시 신청 확인",
    target: "소득인정액 기준 충족 가구",
    amount: "임차료 또는 수선유지비 지원",
    link: "https://www.bokjiro.go.kr/",
    sourceName: "복지로",
    sourceUrl: "https://www.bokjiro.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "근로장려금",
    category: "복지혜택",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "국세청 신청기간 확인",
    target: "소득요건 충족 근로·사업 가구",
    amount: "가구유형별 차등 지급",
    link: "./posts/earned-income-tax-credit.html",
    sourceName: "국세청 홈택스",
    sourceUrl: "https://www.hometax.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "자녀장려금",
    category: "복지혜택",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "국세청 신청기간 확인",
    target: "부양자녀가 있는 저소득 가구",
    amount: "자녀 1인당 차등 지급",
    link: "https://www.hometax.go.kr/",
    sourceName: "국세청 홈택스",
    sourceUrl: "https://www.hometax.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "평생교육바우처",
    category: "복지혜택",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "공식 공고 확인",
    target: "교육 취약계층 성인",
    amount: "교육비 바우처 지원",
    link: "https://www.lllcard.kr/",
    sourceName: "평생교육바우처",
    sourceUrl: "https://www.lllcard.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "부산 청년 디딤돌카드",
    category: "지역별 지원금",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "부산시 공고 확인",
    target: "부산 거주 미취업 청년",
    amount: "활동비 지원",
    link: "https://www.busan.go.kr/",
    sourceName: "부산광역시",
    sourceUrl: "https://www.busan.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "인천 청년 자격증 응시료 지원",
    category: "지역별 지원금",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "인천시 공고 확인",
    target: "인천 거주 청년",
    amount: "응시료 일부 지원",
    link: "https://www.incheon.go.kr/",
    sourceName: "인천광역시",
    sourceUrl: "https://www.incheon.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "대전 청년 월세지원",
    category: "지역별 지원금",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "대전시 공고 확인",
    target: "대전 거주 청년",
    amount: "월세 일부 지원",
    link: "https://www.daejeon.go.kr/",
    sourceName: "대전광역시",
    sourceUrl: "https://www.daejeon.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "청년내일채움공제 안내",
    category: "청년지원",
    categoryTone: "blue",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "공식 안내 확인",
    target: "청년 근로자",
    amount: "공제형 자산형성 지원",
    link: "./posts/youth-tomorrow-deduction.html",
    sourceName: "고용노동부",
    sourceUrl: "https://www.moel.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "청년 국가기술자격시험 응시료 지원",
    category: "청년지원",
    categoryTone: "blue",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "한국산업인력공단 확인",
    target: "국가기술자격 응시 청년",
    amount: "응시료 일부 지원",
    link: "https://www.q-net.or.kr/",
    sourceName: "Q-Net",
    sourceUrl: "https://www.q-net.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "청년 마음건강 지원사업",
    category: "청년지원",
    categoryTone: "blue",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "복지로 또는 지자체 확인",
    target: "심리상담이 필요한 청년",
    amount: "전문 심리상담 바우처",
    link: "https://www.bokjiro.go.kr/",
    sourceName: "복지로",
    sourceUrl: "https://www.bokjiro.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "청년 주거급여 분리지급",
    category: "청년지원",
    categoryTone: "blue",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "상시 신청 확인",
    target: "부모와 따로 거주하는 청년",
    amount: "임차료 지원",
    link: "https://www.bokjiro.go.kr/",
    sourceName: "복지로",
    sourceUrl: "https://www.bokjiro.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "청년내일저축계좌",
    category: "청년지원",
    categoryTone: "blue",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "복지로 모집공고 확인",
    target: "소득요건 충족 청년",
    amount: "근로소득장려금 매칭 지원",
    link: "https://www.bokjiro.go.kr/",
    sourceName: "복지로",
    sourceUrl: "https://www.bokjiro.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "소상공인 전기요금 특별지원",
    category: "소상공인",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "공식 접수일정 확인",
    target: "전기요금 부담 소상공인",
    amount: "전기요금 일부 지원",
    link: "https://www.sbiz24.kr/",
    sourceName: "소상공인24",
    sourceUrl: "https://www.sbiz24.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "소상공인 컨설팅 지원사업",
    category: "소상공인",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "기관별 공고 확인",
    target: "경영개선 희망 소상공인",
    amount: "전문 컨설팅 지원",
    link: "https://www.sbiz.or.kr/",
    sourceName: "소상공인시장진흥공단",
    sourceUrl: "https://www.sbiz.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "소상공인 온라인 판로지원",
    category: "소상공인",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "소상공인24 공고 확인",
    target: "온라인 진출 희망 소상공인",
    amount: "판로·마케팅 지원",
    link: "./posts/small-business-online-sales.html",
    sourceName: "소상공인24",
    sourceUrl: "https://www.sbiz24.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "소공인 클린제조환경 조성",
    category: "소상공인",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "공식 공고 확인",
    target: "제조업 소공인",
    amount: "작업환경 개선 지원",
    link: "https://www.sbiz.or.kr/",
    sourceName: "소상공인시장진흥공단",
    sourceUrl: "https://www.sbiz.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "신사업창업사관학교",
    category: "창업지원",
    categoryTone: "orange",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "모집공고 확인",
    target: "예비창업자",
    amount: "교육·점포체험·사업화 지원",
    link: "https://www.sbiz.or.kr/",
    sourceName: "소상공인시장진흥공단",
    sourceUrl: "https://www.sbiz.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "민관협력 오픈이노베이션 지원",
    category: "창업지원",
    categoryTone: "orange",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "K-Startup 공고 확인",
    target: "스타트업 및 창업기업",
    amount: "사업화·협업 프로그램",
    link: "https://www.k-startup.go.kr/",
    sourceName: "K-Startup",
    sourceUrl: "https://www.k-startup.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "창업성장기술개발사업",
    category: "창업지원",
    categoryTone: "orange",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "중소기업기술개발 공고 확인",
    target: "기술 기반 창업기업",
    amount: "R&D 자금 지원",
    link: "https://www.smtech.go.kr/",
    sourceName: "중소기업기술개발사업",
    sourceUrl: "https://www.smtech.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "TIPS 프로그램",
    category: "창업지원",
    categoryTone: "orange",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "운영사 및 공고 확인",
    target: "기술창업 스타트업",
    amount: "투자연계 R&D 지원",
    link: "./posts/tips-program.html",
    sourceName: "TIPS",
    sourceUrl: "https://www.jointips.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "신혼부부 버팀목 전세자금",
    category: "주거지원",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "주택도시기금 확인",
    target: "신혼부부 무주택 세대주",
    amount: "전세자금 대출 지원",
    link: "https://nhuf.molit.go.kr/",
    sourceName: "주택도시기금",
    sourceUrl: "https://nhuf.molit.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "청년 월세 특별지원",
    category: "주거지원",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "복지로 공고 확인",
    target: "무주택 청년",
    amount: "월세 일부 지원",
    link: "./posts/youth-rent-special-support.html",
    sourceName: "복지로",
    sourceUrl: "https://www.bokjiro.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "LH 청년전세임대",
    category: "주거지원",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "LH 모집공고 확인",
    target: "대학생·취업준비생·청년",
    amount: "전세임대 지원",
    link: "https://apply.lh.or.kr/",
    sourceName: "LH 청약플러스",
    sourceUrl: "https://apply.lh.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "행복주택 입주자 모집",
    category: "주거지원",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "LH·SH 공고 확인",
    target: "청년·신혼부부·고령자",
    amount: "공공임대주택 공급",
    link: "https://apply.lh.or.kr/",
    sourceName: "LH 청약플러스",
    sourceUrl: "https://apply.lh.or.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "기초생활보장 생계급여",
    category: "복지혜택",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "상시 신청 확인",
    target: "소득인정액 기준 충족 가구",
    amount: "생계급여 지원",
    link: "https://www.bokjiro.go.kr/",
    sourceName: "복지로",
    sourceUrl: "https://www.bokjiro.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "문화누리카드",
    category: "복지혜택",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "연도별 이용기간 확인",
    target: "기초생활수급자·차상위계층",
    amount: "문화예술·여행·체육 바우처",
    link: "./posts/culture-nuri-card.html",
    sourceName: "문화누리",
    sourceUrl: "https://www.mnuri.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "아이돌봄서비스 정부지원",
    category: "복지혜택",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "상시 신청 확인",
    target: "돌봄이 필요한 가정",
    amount: "돌봄 이용요금 일부 지원",
    link: "https://www.idolbom.go.kr/",
    sourceName: "아이돌봄서비스",
    sourceUrl: "https://www.idolbom.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "장애인활동지원",
    category: "복지혜택",
    categoryTone: "purple",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "상시 신청 확인",
    target: "활동지원이 필요한 장애인",
    amount: "활동지원급여 제공",
    link: "https://www.bokjiro.go.kr/",
    sourceName: "복지로",
    sourceUrl: "https://www.bokjiro.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "서울시 희망두배 청년통장",
    category: "지역별 지원금",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "서울시 공고 확인",
    target: "서울 거주 근로 청년",
    amount: "저축액 매칭 지원",
    link: "./posts/seoul-youth-savings.html",
    sourceName: "청년몽땅정보통",
    sourceUrl: "https://youth.seoul.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "경기도 청년 노동자 통장",
    category: "지역별 지원금",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "경기도 공고 확인",
    target: "경기도 거주 청년 노동자",
    amount: "자산형성 지원",
    link: "https://youth.gg.go.kr/",
    sourceName: "경기청년포털",
    sourceUrl: "https://youth.gg.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "대구 청년수당",
    category: "지역별 지원금",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "대구시 공고 확인",
    target: "대구 거주 청년",
    amount: "활동지원금",
    link: "https://www.daegu.go.kr/",
    sourceName: "대구광역시",
    sourceUrl: "https://www.daegu.go.kr/",
    updatedAt: "2026-06-23"
  },
  {
    title: "광주 청년드림수당",
    category: "지역별 지원금",
    categoryTone: "mint",
    status: "신청중",
    statusTone: "green",
    group: "open",
    periodLabel: "기간",
    period: "광주시 공고 확인",
    target: "광주 거주 미취업 청년",
    amount: "구직활동비 지원",
    link: "https://www.gwangju.go.kr/",
    sourceName: "광주광역시",
    sourceUrl: "https://www.gwangju.go.kr/",
    updatedAt: "2026-06-23"
  }
];
