window.SUPPORT_PROGRAMS = [
  ["youth-rent","청년 월세 한시 특별지원","청년지원","blue","신청중","green","open","기간","공식 공고 확인","만 19~34세 무주택 청년","월 최대 20만원","복지로","https://www.bokjiro.go.kr/"],
  ["kua-youth","국민취업지원제도 청년층 지원","청년지원","blue","신청중","green","open","기간","상시 신청 확인","취업을 준비하는 청년","구직촉진수당 및 취업지원서비스","국민취업지원제도","https://www.kua.go.kr/"],
  ["youth-leap-account","청년도약계좌","청년지원","blue","신청중","green","open","기간","월별 신청기간 확인","소득요건을 충족한 청년","정부기여금 및 비과세 혜택","서민금융진흥원","https://ylaccount.kinfa.or.kr/"],
  ["youth-job-allowance","청년 취업성공수당","청년지원","blue","마감임박","amber","deadline","마감","공식 공고 확인","취업지원 프로그램 참여 청년","최대 150만원","고용24","https://www.work24.go.kr/"],
  ["youth-savings","청년내일저축계좌","청년지원","blue","신청중","green","open","기간","복지로 모집공고 확인","근로 중인 저소득 청년","근로소득장려금 매칭 지원","복지로","https://www.bokjiro.go.kr/"],
  ["smallbiz-digital","소상공인 디지털 전환 지원사업","소상공인","mint","신청중","green","open","기간","기관별 공고 확인","소상공인","최대 100만원","소상공인24","https://www.sbiz24.kr/"],
  ["smallbiz-policy-fund","소상공인 정책자금","소상공인","mint","신청중","green","open","기간","자금별 접수일정 확인","소상공인 및 자영업자","정책자금 융자","소상공인정책자금","https://ols.semas.or.kr/"],
  ["smallbiz-electricity","소상공인 전기요금 특별지원","소상공인","mint","신청중","green","open","기간","공식 접수일정 확인","전기요금 부담 소상공인","전기요금 일부 지원","소상공인24","https://www.sbiz24.kr/"],
  ["smallbiz-online","소상공인 온라인 판로지원","소상공인","mint","신청중","green","open","기간","소상공인24 공고 확인","온라인 진출 희망 소상공인","판로·마케팅 지원","소상공인24","https://www.sbiz24.kr/"],
  ["startup-package","초기 창업패키지 지원사업","창업지원","orange","신청중","green","open","기간","K-Startup 공고 확인","예비창업자, 3년 이내 창업기업","최대 1억원","K-Startup","https://www.k-startup.go.kr/"],
  ["pre-startup","예비창업패키지","창업지원","orange","신청중","green","open","기간","K-Startup 공고 확인","예비창업자","사업화 자금 지원","K-Startup","https://www.k-startup.go.kr/"],
  ["startup-leap","창업 도약패키지 지원사업","창업지원","orange","마감임박","amber","deadline","마감","K-Startup 공고 확인","3~7년 이내 창업기업","최대 3억원","K-Startup","https://www.k-startup.go.kr/"],
  ["tips","TIPS 프로그램","창업지원","orange","신청중","green","open","기간","운영사 및 공고 확인","기술창업 스타트업","투자연계 R&D 지원","TIPS","https://www.jointips.or.kr/"],
  ["jeonse-loan","버팀목 전세자금대출","주거지원","purple","신청중","green","open","기간","상품별 확인","무주택 세대주","전세자금 대출 지원","주택도시기금","https://nhuf.molit.go.kr/"],
  ["newlywed-jeonse","신혼부부 전세자금 대출이자 지원","주거지원","purple","신청중","green","open","기간","지자체 공고 확인","신혼부부","연 최대 100만원","정부24","https://www.gov.kr/"],
  ["housing-benefit","주거급여","주거지원","purple","신청중","green","open","기간","상시 신청 확인","소득인정액 기준 충족 가구","임차료 또는 수선유지비 지원","복지로","https://www.bokjiro.go.kr/"],
  ["youth-jeonse-return","청년 전세보증금 반환보증 보증료 지원","주거지원","purple","마감임박","amber","deadline","마감","정부24 공고 확인","청년 임차인","최대 30만원","정부24","https://www.gov.kr/"],
  ["earned-income-tax-credit","근로장려금","복지혜택","purple","신청중","green","open","기간","국세청 신청기간 확인","소득요건 충족 근로·사업 가구","가구유형별 차등 지급","국세청 홈택스","https://www.hometax.go.kr/"],
  ["culture-nuri","문화누리카드","복지혜택","purple","신청중","green","open","기간","연도별 이용기간 확인","기초생활수급자·차상위계층","문화예술·여행·체육 바우처","문화누리","https://www.mnuri.kr/"],
  ["energy-voucher","에너지바우처","복지혜택","purple","신청중","green","open","기간","공식 공고 확인","취약계층 가구","가구별 차등 지원","에너지바우처","https://www.energyv.or.kr/"],
  ["child-care","아이돌봄서비스 정부지원","복지혜택","purple","신청중","green","open","기간","상시 신청 확인","돌봄이 필요한 가정","돌봄 이용요금 일부 지원","아이돌봄서비스","https://www.idolbom.go.kr/"],
  ["seoul-youth","서울시 청년수당","지역별 지원금","mint","신청중","green","open","기간","서울시 공고 확인","서울 거주 미취업 청년","공고별 확인","청년몽땅정보통","https://youth.seoul.go.kr/"],
  ["gg-youth-income","경기도 청년기본소득","지역별 지원금","mint","신청중","green","open","기간","경기도 공고 확인","경기도 거주 청년","분기별 지원","잡아바 어플라이","https://apply.jobaba.net/"],
  ["busan-youth","부산 청년 디딤돌카드","지역별 지원금","mint","신청중","green","open","기간","부산시 공고 확인","부산 거주 미취업 청년","활동비 지원","부산광역시","https://www.busan.go.kr/"]
].map(function (item) {
  return {
    slug: item[0],
    title: item[1],
    category: item[2],
    categoryTone: item[3],
    status: item[4],
    statusTone: item[5],
    group: item[6],
    periodLabel: item[7],
    period: item[8],
    target: item[9],
    amount: item[10],
    sourceName: item[11],
    sourceUrl: item[12],
    link: "./article.html?slug=" + item[0],
    updatedAt: "2026-06-23"
  };
});
