(function () {
  var pages = {
    "youth-rent": "youth-rent.html",
    "kua-youth": "kua-youth.html",
    "youth-leap-account": "youth-leap-account.html",
    "youth-job": "youth-job.html",
    "youth-saving": "youth-saving.html",
    "youth-mind": "youth-mind.html",
    "youth-exam-fee": "youth-exam-fee.html",
    "youth-job-dojak": "youth-job-dojak.html",
    "youth-housing-separate": "youth-housing-separate.html",
    "smallbiz-digital": "smallbiz-digital.html",
    "smallbiz-fund": "smallbiz-fund.html",
    "smallbiz-electric": "smallbiz-electric.html",
    "smallbiz-online": "smallbiz-online.html",
    "smallbiz-consulting": "smallbiz-consulting.html",
    "smallbiz-return": "smallbiz-return.html",
    "smallbiz-market": "smallbiz-market.html",
    "smallbiz-clean": "smallbiz-clean.html",
    "startup-basic": "startup-basic.html",
    "startup-pre": "startup-pre.html",
    "startup-leap": "startup-leap.html",
    "tips": "tips.html",
    "startup-school": "startup-school.html",
    "startup-rnd": "startup-rnd.html",
    "startup-retry": "startup-retry.html",
    "startup-open-innovation": "startup-open-innovation.html",
    "jeonse": "jeonse.html",
    "newlywed": "newlywed.html",
    "housing-benefit": "housing-benefit.html",
    "youth-jeonse-guarantee": "youth-jeonse-guarantee.html",
    "lh-youth-jeonse": "lh-youth-jeonse.html",
    "happy-house": "happy-house.html",
    "newlywed-butimok": "newlywed-butimok.html",
    "eitc": "eitc.html",
    "child-tax-credit": "child-tax-credit.html",
    "culture": "culture.html",
    "energy": "energy.html",
    "child-care": "child-care.html",
    "basic-living": "basic-living.html",
    "lifelong-voucher": "lifelong-voucher.html",
    "disabled-activity": "disabled-activity.html",
    "seoul-youth": "seoul-youth.html",
    "seoul-saving": "seoul-saving.html",
    "gg-youth": "gg-youth.html",
    "gg-worker-bank": "gg-worker-bank.html",
    "busan-youth": "busan-youth.html",
    "incheon-exam": "incheon-exam.html",
    "daejeon-rent": "daejeon-rent.html",
    "gwangju-dream": "gwangju-dream.html"
  };

  (window.SUPPORT_PROGRAMS || []).forEach(function (program) {
    if (pages[program.slug]) program.link = "./" + pages[program.slug];
  });
}());
